kind: pipeline
name: default

steps:
  - name: test
    image: golang
    commands:
      - go test ./...

  - name: extractor
    image: akhenakh/safepassage:1.0
    pull: always
    environment:
      my_secret:
        from_secret: my_drone_secret
    settings:
      another_secret:
        from_secret: my_other_drone_secret
      secrets:
        - MY_SECRET
        - ANOTHER_SECRET
      pubkey: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: BCPG C# v1.6.1.0

        mQENBF7+iUMBCACOCMu00j9rxie1JK5diFdexMbuQZbzJfBCWUyov3UgfTwXyoKF
        IMF2PPop/tWFpHd5tRVwys05m634oEW4/Ufgu38W9pT9QYojfE/Nkq2nzpeSkvHm
        HYBhG9W61twIBaGWiA0C3k/pBZygp1Fm1CciWGrYROhDgczZ9s+hjk6gq2aYYKeY
        wTVaG5L42TSAUaoJWkgxNpgaGVREQ+dwsvy5/XmN7iVcjQWY82pBi7jQmJ2gCY58
        EVqcpqCuY54f1bZkHBXoPpN2BIQ+Ekk/7Qss+HeNNcV0cPkpdkMKxokpTQxv+cHf
        Bjj5eB46eoZr/v/pFQqaax2zi86HB+UdqEkHABEBAAG0DXRlc3RAdGVzdC5vcmeJ
        ARwEEAECAAYFAl7+iUMACgkQjTK7M62UXpWJ4Af8CMB59RJWCClf6ZgcuAP1eocA
        yfK+ouwL9xz2bCqp7OlYmEgvE6W25m97gFUGXKG/qWy9zVYfqYk0qRFrdLXLfB2b
        wzWn0x5DABog3scglpJ7mjLR09NmRMu+jKMzqsvG5H2AGwJbjQwWfrK+nTmw2wR5
        SikVdmH8RAmngSDrrBUtW17yxMgpEvhQ1ZLdiIIikddQEyrYH/sZKvCjCiHykxV1
        rZJYD/cd3r8X7fl/pnfS43y1yRkG8MeUghtUI3PSMubNX70jE6w+n3K9lbDAV5T9
        zkuaUUS4lFuckkdbXmWpv5/sc/Fz02sHk5PnpES6iJJ2ayIg7jrKjUijeicKrw==
        =3QwS
        -----END PGP PUBLIC KEY BLOCK-----